services:
  postgres:
    image: postgres:16-alpine
    container_name: hms-postgres
    environment:
      POSTGRES_DB: hms_db
      POSTGRES_USER: hms_user
      POSTGRES_PASSWORD: hms_pass
    ports:
      - "5432:5432"
    volumes:
      - hms_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hms_user -d hms_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  hms_pg_data:
